-- Private storage bucket for uploaded documents (payslips, IDs, mortgage
-- payoff statements, etc.) — replaces Base44's UploadFile/UploadPrivateFile.
--
-- No public/anon RLS policies are added here: every access path goes through
-- either the service-role client (ctx.supabaseAdmin in the Edge Functions,
-- which bypasses RLS by design) or a short-lived signed URL generated by
-- those same functions. There is no direct anonymous read/write path to
-- this bucket, matching the sensitivity of the documents it holds.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;
